[package]
name = "reproduce-autocxx-overload-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.27.0"
cxx = { version = "1.0.124", features = ["c++14"] }

[build-dependencies]
autocxx-build = "0.27.0"
